{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotreba.fullname" . }}-postgresql
  labels:
    {{- include "spotreba.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "spotreba.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
