apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotreba.fullname" . }}
  labels:
    {{- include "spotreba.labels" . | nindent 4 }}
type: Opaque
stringData:
  rails-secret-key-base: {{ .Values.rails.secretKeyBase | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
